# Generated by Django 3.2.25 on 2024-08-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
