# Generated by Django 3.2.25 on 2024-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_follow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='to_user',
        ),
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], max_length=10),
        ),
    ]
